port = 8080;
serv_name = HTML_Example.html;
error_page = 404 404.html;
error_page = 500 501 500.html
client_max_body_size = 10M;

location = /bonjour;
{
allow_methods = GET POST DELETE; #methodes autorisées sur la route?
root = /exemple; #racine du repertoire
autoindex = on; # affiche ou pas les repertoire si demande repertoire
index = index.html; #fichier par defaut si demande un repertoire
upload_store = /exemple; #stockage fichier recup par get
cgi_pass = #peut etre supprimee si on n'execute que du py normalement
cgi_dir = /exemple/bin;

}

location /cgi {
cgi = on
}

