
server {
    port = 8080;
    serv_name = HTML_Example.html;
    error_page = 404.html;
    client_max_body_size = 10M;
}

server{
    port = 80;
    serv_name = HTML_Example;
    error_page = 404 404.html;
    error_page = 500 500.html
}

