port = 8080;
serv_name = webserv_test;
client_max_body_size = 10M;
error_page = 404 403 /errors/4xx.html;
error_page = 500 /errors/500.html;

location = /kapouet; 
{
    allow_methods = GET POST;
    root = /tmp/www;
    autoindex = on;
    index = index.html;
    cgi_pass = .py /usr/bin/python3;
    cgi_dir = /tmp/www/cgi-bin;
}
