port = 8082;
serv_name = HTML_Example.html;
error_page = 400 server_files/errors/400.html;
error_page = 403 server_files/errors/403.html;
error_page = 404 server_files/errors/404.html;
error_page = 405 server_files/errors/405.html;
error_page = 408 server_files/errors/408.html;
error_page = 411 server_files/errors/411.html;
error_page = 413 server_files/errors/413.html;
error_page = 414 server_files/errors/414.html;
error_page = 431 server_files/errors/431.html;
error_page = 500 server_files/errors/500.html;
error_page = 501 server_files/errors/501.html;
error_page = 502 server_files/errors/502.html;
error_page = 503 server_files/errors/503.html;
error_page = 504 server_files/errors/504.html;
error_page = 505 server_files/errors/505.html;
client_max_body_size = 10M;

location = /old_path; #gere les redirections
{
    return = 301 https://example.com/new-path;
}

location = /;
{
allow_methods = GET POST DELETE; #methodes autorisées sur la route?
root = server_files; #racine du repertoire
autoindex = on; # affiche ou pas les repertoire si demande repertoire
index = HTML_Example.html; #fichier par defaut si demande un repertoire
}

location  = /cgi;
{
    cgi = on;
}

#faire fonction qui vient voir les redirections et retournée la valeur redirigee